import {
   CLEAR_EPOCH_DATA,
   SET_EPOCH_DATA,
   POPULATE_EPOCH_DATA,
} from "./actions";

const initialState = [];

export default (state = initialState, action) => {
   switch (action.type) {
      case SET_EPOCH_DATA:
         return { ...state, ...action.data };

      case CLEAR_EPOCH_DATA:
         return { ...initialState };

      case POPULATE_EPOCH_DATA:
         return [
            {
               active_calories: 7,
               active_time: 82,
               activity_type: "WALKING",
               distance: 157.39,
               duration: 900,
               end_time: "2021-05-27 11:45:00",
               intensity: "HIGHLY_ACTIVE",
               max_motion_intensity: 3.0,
               mean_motion_intensity: 3.0,
               met: 4.40728,
               participant:
                  "<physioq_project_record_service.db_models.db_participant.Participant object at 0x7fb009ce17f0>",
               start_time: "2021-05-27 11:30:00",
               start_time_offset: -14400,
               steps: 185,
               summary_user_id: "x3a123fb",
            },
            {
               active_calories: 0,
               active_time: 818,
               activity_type: "SEDENTARY",
               distance: 0.0,
               duration: 900,
               end_time: "2021-05-27 11:45:00",
               intensity: "SEDENTARY",
               max_motion_intensity: 5.0,
               mean_motion_intensity: 0.0,
               met: 1.0,
               participant:
                  "<physioq_project_record_service.db_models.db_participant.Participant object at 0x7fb009ce17f0>",
               start_time: "2021-05-27 11:30:00",
               start_time_offset: -14400,
               steps: 0,
               summary_user_id: "x3a123fb",
            },
            {
               active_calories: 43,
               active_time: 601,
               activity_type: "WALKING",
               distance: 428.8,
               duration: 900,
               end_time: "2021-05-27 12:00:00",
               intensity: "ACTIVE",
               max_motion_intensity: 2.0,
               mean_motion_intensity: 1.99501,
               met: 3.85573,
               participant:
                  "<physioq_project_record_service.db_models.db_participant.Participant object at 0x7fb009ce17f0>",
               start_time: "2021-05-27 11:45:00",
               start_time_offset: -14400,
               steps: 504,
               summary_user_id: "x3a123fb",
            },
            {
               active_calories: 0,
               active_time: 299,
               activity_type: "SEDENTARY",
               distance: 0.0,
               duration: 900,
               end_time: "2021-05-27 12:00:00",
               intensity: "SEDENTARY",
               max_motion_intensity: 4.0,
               mean_motion_intensity: 0.0,
               met: 1.0,
               participant:
                  "<physioq_project_record_service.db_models.db_participant.Participant object at 0x7fb009ce17f0>",
               start_time: "2021-05-27 11:45:00",
               start_time_offset: -14400,
               steps: 0,
               summary_user_id: "x3a123fb",
            },
            {
               active_calories: 0,
               active_time: 900,
               activity_type: "SEDENTARY",
               distance: 0.0,
               duration: 900,
               end_time: "2021-05-27 12:15:00",
               intensity: "SEDENTARY",
               max_motion_intensity: 3.0,
               mean_motion_intensity: 0.0,
               met: 1.0,
               participant:
                  "<physioq_project_record_service.db_models.db_participant.Participant object at 0x7fb009ce17f0>",
               start_time: "2021-05-27 12:00:00",
               start_time_offset: -14400,
               steps: 0,
               summary_user_id: "x3a123fb",
            },
            {
               active_calories: 0,
               active_time: 900,
               activity_type: "SEDENTARY",
               distance: 0.0,
               duration: 900,
               end_time: "2021-05-27 12:30:00",
               intensity: "SEDENTARY",
               max_motion_intensity: 3.0,
               mean_motion_intensity: 0.0,
               met: 1.0,
               participant:
                  "<physioq_project_record_service.db_models.db_participant.Participant object at 0x7fb009ce17f0>",
               start_time: "2021-05-27 12:15:00",
               start_time_offset: -14400,
               steps: 0,
               summary_user_id: "x3a123fb",
            },
            {
               active_calories: 0,
               active_time: 900,
               activity_type: "SEDENTARY",
               distance: 0.0,
               duration: 900,
               end_time: "2021-05-27 12:45:00",
               intensity: "SEDENTARY",
               max_motion_intensity: 3.0,
               mean_motion_intensity: 0.0,
               met: 1.0,
               participant:
                  "<physioq_project_record_service.db_models.db_participant.Participant object at 0x7fb009ce17f0>",
               start_time: "2021-05-27 12:30:00",
               start_time_offset: -14400,
               steps: 0,
               summary_user_id: "x3a123fb",
            },
            {
               active_calories: 0,
               active_time: 15,
               activity_type: "WALKING",
               distance: 11.06,
               duration: 900,
               end_time: "2021-05-27 13:00:00",
               intensity: "ACTIVE",
               max_motion_intensity: 2.0,
               mean_motion_intensity: 2.0,
               met: 1.0,
               participant:
                  "<physioq_project_record_service.db_models.db_participant.Participant object at 0x7fb009ce17f0>",
               start_time: "2021-05-27 12:45:00",
               start_time_offset: -14400,
               steps: 13,
               summary_user_id: "x3a123fb",
            },
            {
               active_calories: 0,
               active_time: 885,
               activity_type: "SEDENTARY",
               distance: 0.0,
               duration: 900,
               end_time: "2021-05-27 13:00:00",
               intensity: "SEDENTARY",
               max_motion_intensity: 3.0,
               mean_motion_intensity: 0.0,
               met: 1.0,
               participant:
                  "<physioq_project_record_service.db_models.db_participant.Participant object at 0x7fb009ce17f0>",
               start_time: "2021-05-27 12:45:00",
               start_time_offset: -14400,
               steps: 0,
               summary_user_id: "x3a123fb",
            },
            {
               active_calories: 0,
               active_time: 30,
               activity_type: "WALKING",
               distance: 29.78,
               duration: 900,
               end_time: "2021-05-27 13:15:00",
               intensity: "ACTIVE",
               max_motion_intensity: 3.0,
               mean_motion_intensity: 3.0,
               met: 1.0,
               participant:
                  "<physioq_project_record_service.db_models.db_participant.Participant object at 0x7fb009ce17f0>",
               start_time: "2021-05-27 13:00:00",
               start_time_offset: -14400,
               steps: 35,
               summary_user_id: "x3a123fb",
            },
            {
               active_calories: 0,
               active_time: 870,
               activity_type: "SEDENTARY",
               distance: 0.0,
               duration: 900,
               end_time: "2021-05-27 13:15:00",
               intensity: "SEDENTARY",
               max_motion_intensity: 4.0,
               mean_motion_intensity: 0.0,
               met: 1.0,
               participant:
                  "<physioq_project_record_service.db_models.db_participant.Participant object at 0x7fb009ce17f0>",
               start_time: "2021-05-27 13:00:00",
               start_time_offset: -14400,
               steps: 0,
               summary_user_id: "x3a123fb",
            },
            {
               active_calories: 0,
               active_time: 900,
               activity_type: "SEDENTARY",
               distance: 0.0,
               duration: 900,
               end_time: "2021-05-27 13:30:00",
               intensity: "SEDENTARY",
               max_motion_intensity: 3.0,
               mean_motion_intensity: 0.0,
               met: 1.0,
               participant:
                  "<physioq_project_record_service.db_models.db_participant.Participant object at 0x7fb009ce17f0>",
               start_time: "2021-05-27 13:15:00",
               start_time_offset: -14400,
               steps: 0,
               summary_user_id: "x3a123fb",
            },
            {
               active_calories: 0,
               active_time: 15,
               activity_type: "WALKING",
               distance: 12.76,
               duration: 900,
               end_time: "2021-05-27 13:45:00",
               intensity: "ACTIVE",
               max_motion_intensity: 4.0,
               mean_motion_intensity: 4.0,
               met: 1.0,
               participant:
                  "<physioq_project_record_service.db_models.db_participant.Participant object at 0x7fb009ce17f0>",
               start_time: "2021-05-27 13:30:00",
               start_time_offset: -14400,
               steps: 15,
               summary_user_id: "x3a123fb",
            },
            {
               active_calories: 0,
               active_time: 885,
               activity_type: "SEDENTARY",
               distance: 0.0,
               duration: 900,
               end_time: "2021-05-27 13:45:00",
               intensity: "SEDENTARY",
               max_motion_intensity: 3.0,
               mean_motion_intensity: 0.0,
               met: 1.0,
               participant:
                  "<physioq_project_record_service.db_models.db_participant.Participant object at 0x7fb009ce17f0>",
               start_time: "2021-05-27 13:30:00",
               start_time_offset: -14400,
               steps: 0,
               summary_user_id: "x3a123fb",
            },
            {
               active_calories: 0,
               active_time: 900,
               activity_type: "SEDENTARY",
               distance: 0.0,
               duration: 900,
               end_time: "2021-05-27 14:00:00",
               intensity: "SEDENTARY",
               max_motion_intensity: 3.0,
               mean_motion_intensity: 0.0,
               met: 1.0,
               participant:
                  "<physioq_project_record_service.db_models.db_participant.Participant object at 0x7fb009ce17f0>",
               start_time: "2021-05-27 13:45:00",
               start_time_offset: -14400,
               steps: 0,
               summary_user_id: "x3a123fb",
            },
            {
               active_calories: 1,
               active_time: 60,
               activity_type: "WALKING",
               distance: 58.71,
               duration: 900,
               end_time: "2021-05-27 14:15:00",
               intensity: "ACTIVE",
               max_motion_intensity: 3.0,
               mean_motion_intensity: 3.0,
               met: 1.66523,
               participant:
                  "<physioq_project_record_service.db_models.db_participant.Participant object at 0x7fb009ce17f0>",
               start_time: "2021-05-27 14:00:00",
               start_time_offset: -14400,
               steps: 69,
               summary_user_id: "x3a123fb",
            },
            {
               active_calories: 0,
               active_time: 840,
               activity_type: "SEDENTARY",
               distance: 0.0,
               duration: 900,
               end_time: "2021-05-27 14:15:00",
               intensity: "SEDENTARY",
               max_motion_intensity: 3.0,
               mean_motion_intensity: 0.0,
               met: 1.0,
               participant:
                  "<physioq_project_record_service.db_models.db_participant.Participant object at 0x7fb009ce17f0>",
               start_time: "2021-05-27 14:00:00",
               start_time_offset: -14400,
               steps: 0,
               summary_user_id: "x3a123fb",
            },
            {
               active_calories: 0,
               active_time: 900,
               activity_type: "SEDENTARY",
               distance: 0.0,
               duration: 900,
               end_time: "2021-05-27 14:30:00",
               intensity: "SEDENTARY",
               max_motion_intensity: 3.0,
               mean_motion_intensity: 0.0,
               met: 1.0,
               participant:
                  "<physioq_project_record_service.db_models.db_participant.Participant object at 0x7fb009ce17f0>",
               start_time: "2021-05-27 14:15:00",
               start_time_offset: -14400,
               steps: 0,
               summary_user_id: "x3a123fb",
            },
            {
               active_calories: 0,
               active_time: 900,
               activity_type: "SEDENTARY",
               distance: 0.0,
               duration: 900,
               end_time: "2021-05-27 14:45:00",
               intensity: "SEDENTARY",
               max_motion_intensity: 3.0,
               mean_motion_intensity: 0.0,
               met: 1.0,
               participant:
                  "<physioq_project_record_service.db_models.db_participant.Participant object at 0x7fb009ce17f0>",
               start_time: "2021-05-27 14:30:00",
               start_time_offset: -14400,
               steps: 0,
               summary_user_id: "x3a123fb",
            },
            {
               active_calories: 6,
               active_time: 90,
               activity_type: "WALKING",
               distance: 74.02,
               duration: 900,
               end_time: "2021-05-27 15:00:00",
               intensity: "ACTIVE",
               max_motion_intensity: 3.0,
               mean_motion_intensity: 3.0,
               met: 3.66092,
               participant:
                  "<physioq_project_record_service.db_models.db_participant.Participant object at 0x7fb009ce17f0>",
               start_time: "2021-05-27 14:45:00",
               start_time_offset: -14400,
               steps: 87,
               summary_user_id: "x3a123fb",
            },
            {
               active_calories: 0,
               active_time: 810,
               activity_type: "SEDENTARY",
               distance: 0.0,
               duration: 900,
               end_time: "2021-05-27 15:00:00",
               intensity: "SEDENTARY",
               max_motion_intensity: 4.0,
               mean_motion_intensity: 0.0,
               met: 1.0,
               participant:
                  "<physioq_project_record_service.db_models.db_participant.Participant object at 0x7fb009ce17f0>",
               start_time: "2021-05-27 14:45:00",
               start_time_offset: -14400,
               steps: 0,
               summary_user_id: "x3a123fb",
            },
            {
               active_calories: 0,
               active_time: 900,
               activity_type: "SEDENTARY",
               distance: 0.0,
               duration: 900,
               end_time: "2021-05-27 15:15:00",
               intensity: "SEDENTARY",
               max_motion_intensity: 4.0,
               mean_motion_intensity: 0.0,
               met: 1.0,
               participant:
                  "<physioq_project_record_service.db_models.db_participant.Participant object at 0x7fb009ce17f0>",
               start_time: "2021-05-27 15:00:00",
               start_time_offset: -14400,
               steps: 0,
               summary_user_id: "x3a123fb",
            },
            {
               active_calories: 0,
               active_time: 900,
               activity_type: "SEDENTARY",
               distance: 0.0,
               duration: 900,
               end_time: "2021-05-27 15:30:00",
               intensity: "SEDENTARY",
               max_motion_intensity: 3.0,
               mean_motion_intensity: 0.0,
               met: 1.0,
               participant:
                  "<physioq_project_record_service.db_models.db_participant.Participant object at 0x7fb009ce17f0>",
               start_time: "2021-05-27 15:15:00",
               start_time_offset: -14400,
               steps: 0,
               summary_user_id: "x3a123fb",
            },
            {
               active_calories: 0,
               active_time: 900,
               activity_type: "SEDENTARY",
               distance: 0.0,
               duration: 900,
               end_time: "2021-05-27 15:45:00",
               intensity: "SEDENTARY",
               max_motion_intensity: 3.0,
               mean_motion_intensity: 0.0,
               met: 1.0,
               participant:
                  "<physioq_project_record_service.db_models.db_participant.Participant object at 0x7fb009ce17f0>",
               start_time: "2021-05-27 15:30:00",
               start_time_offset: -14400,
               steps: 0,
               summary_user_id: "x3a123fb",
            },
            {
               active_calories: 0,
               active_time: 900,
               activity_type: "SEDENTARY",
               distance: 0.0,
               duration: 900,
               end_time: "2021-05-27 16:00:00",
               intensity: "SEDENTARY",
               max_motion_intensity: 4.0,
               mean_motion_intensity: 0.0,
               met: 1.0,
               participant:
                  "<physioq_project_record_service.db_models.db_participant.Participant object at 0x7fb009ce17f0>",
               start_time: "2021-05-27 15:45:00",
               start_time_offset: -14400,
               steps: 0,
               summary_user_id: "x3a123fb",
            },
            {
               active_calories: 1,
               active_time: 30,
               activity_type: "WALKING",
               distance: 36.58,
               duration: 900,
               end_time: "2021-05-27 16:15:00",
               intensity: "ACTIVE",
               max_motion_intensity: 2.0,
               mean_motion_intensity: 2.0,
               met: 2.33046,
               participant:
                  "<physioq_project_record_service.db_models.db_participant.Participant object at 0x7fb009ce17f0>",
               start_time: "2021-05-27 16:00:00",
               start_time_offset: -14400,
               steps: 43,
               summary_user_id: "x3a123fb",
            },
            {
               active_calories: 0,
               active_time: 870,
               activity_type: "SEDENTARY",
               distance: 0.0,
               duration: 900,
               end_time: "2021-05-27 16:15:00",
               intensity: "SEDENTARY",
               max_motion_intensity: 4.0,
               mean_motion_intensity: 0.0,
               met: 1.0,
               participant:
                  "<physioq_project_record_service.db_models.db_participant.Participant object at 0x7fb009ce17f0>",
               start_time: "2021-05-27 16:00:00",
               start_time_offset: -14400,
               steps: 0,
               summary_user_id: "x3a123fb",
            },
            {
               active_calories: 5,
               active_time: 115,
               activity_type: "WALKING",
               distance: 133.58,
               duration: 900,
               end_time: "2021-05-27 16:30:00",
               intensity: "ACTIVE",
               max_motion_intensity: 2.0,
               mean_motion_intensity: 2.0,
               met: 2.73538,
               participant:
                  "<physioq_project_record_service.db_models.db_participant.Participant object at 0x7fb009ce17f0>",
               start_time: "2021-05-27 16:15:00",
               start_time_offset: -14400,
               steps: 157,
               summary_user_id: "x3a123fb",
            },
            {
               active_calories: 0,
               active_time: 785,
               activity_type: "SEDENTARY",
               distance: 0.0,
               duration: 900,
               end_time: "2021-05-27 16:30:00",
               intensity: "SEDENTARY",
               max_motion_intensity: 4.0,
               mean_motion_intensity: 0.0,
               met: 1.0,
               participant:
                  "<physioq_project_record_service.db_models.db_participant.Participant object at 0x7fb009ce17f0>",
               start_time: "2021-05-27 16:15:00",
               start_time_offset: -14400,
               steps: 0,
               summary_user_id: "x3a123fb",
            },
            {
               active_calories: 1,
               active_time: 49,
               activity_type: "WALKING",
               distance: 30.63,
               duration: 900,
               end_time: "2021-05-27 16:45:00",
               intensity: "ACTIVE",
               max_motion_intensity: 2.0,
               mean_motion_intensity: 1.91837,
               met: 1.81457,
               participant:
                  "<physioq_project_record_service.db_models.db_participant.Participant object at 0x7fb009ce17f0>",
               start_time: "2021-05-27 16:30:00",
               start_time_offset: -14400,
               steps: 36,
               summary_user_id: "x3a123fb",
            },
            {
               active_calories: 0,
               active_time: 851,
               activity_type: "SEDENTARY",
               distance: 0.0,
               duration: 900,
               end_time: "2021-05-27 16:45:00",
               intensity: "SEDENTARY",
               max_motion_intensity: 5.0,
               mean_motion_intensity: 0.0,
               met: 1.0,
               participant:
                  "<physioq_project_record_service.db_models.db_participant.Participant object at 0x7fb009ce17f0>",
               start_time: "2021-05-27 16:30:00",
               start_time_offset: -14400,
               steps: 0,
               summary_user_id: "x3a123fb",
            },
            {
               active_calories: 0,
               active_time: 480,
               activity_type: "SEDENTARY",
               distance: 0.0,
               duration: 480,
               end_time: "2021-05-27 16:53:00",
               intensity: "SEDENTARY",
               max_motion_intensity: 3.0,
               mean_motion_intensity: 0.0,
               met: 1.0,
               participant:
                  "<physioq_project_record_service.db_models.db_participant.Participant object at 0x7fb009ce17f0>",
               start_time: "2021-05-27 16:45:00",
               start_time_offset: -14400,
               steps: 0,
               summary_user_id: "x3a123fb",
            },
         ];

      default:
         return state;
   }
};
